{ modulesPath, ... }:
{
  imports = [
    "${modulesPath}/installer/scan/not-detected.nix"
  ];

  # Virtio guest kernel modules
  boot.initrd.availableKernelModules = [
    "virtio_pci" "virtio_blk" "virtio_scsi"
    "xhci_pci" "sd_mod"
  ];
  boot.kernelModules      = [ ];
  boot.extraModulePackages = [ ];

  # fileSystems and swapDevices are generated by disko (see disko.nix)

  boot.loader.systemd-boot.enable      = true;
  boot.loader.efi.canTouchEfiVariables = true;
}
