{ modulesPath, ... }:
{
  imports = [
    "${modulesPath}/installer/scan/not-detected.nix"
  ];

  boot = {
    initrd.availableKernelModules = [
      "xhci_pci" "ahci" "nvme" "usb_storage" "sd_mod" "tpm_tis" "tpm_crb"
    ];
    kernelModules = [ "kvm-intel" "tpm_tis" "tpm_crb" ];
    extraModulePackages = [ ];
  };

  # fileSystems and swapDevices are generated by disko (see disko.nix)
}
