# Hand-maintained hardware configuration stub.
# Regeneration policy: replace this file with generated hardware config from the
# target machine during install or after hardware topology changes, then review
# and keep only the host-specific settings that should remain hand-maintained.
# Last reviewed: 2026-04-24.
# Run on the installed system: nixos-generate-config --show-hardware-config
# or generate during install: nixos-anywhere --generate-hardware-config nixos-generate-config ...
{ modulesPath, ... }:
{
  imports = [
    "${modulesPath}/installer/scan/not-detected.nix"
  ];

  # fileSystems and swapDevices are generated by disko (see disko.nix)

  boot.loader.systemd-boot.enable = true;
  boot.loader.efi.canTouchEfiVariables = true;
}
