# STUB — replace with real hardware config generated on the target machine.
# Run on the installed system: nixos-generate-config --show-hardware-config
# or generate during install: nixos-anywhere --generate-hardware-config nixos-generate-config ...
{ modulesPath, ... }:
{
  imports = [
    "${modulesPath}/installer/scan/not-detected.nix"
  ];

  # fileSystems and swapDevices are generated by disko (see disko.nix)

  boot.loader.systemd-boot.enable      = true;
  boot.loader.efi.canTouchEfiVariables = true;
}
